### ISSUE TITLE
[Discuss] Are parallel efforts mutually exclusive or complementary?

### ISSUE THREAD

**Issue by timcappalli** [WICG/digital-identities#29]
> Surfaced as a core discussion topic on the first call ([2023-10-04](https://github.com/WICG/identity-credential/wiki/2023-10-04-Meeting-Notes)).

Ex: browser  APIs vs OpenID4VP vs other protocols

**Comment by OR13** [comment]
IMO, they are complementary.

Ideally supporting a safe experience in a browser, and supporting a safe experience in a workload or machine identity context does not require learning, implementing and mastering drastically different protocols.

**Comment by aniltj** [comment]
Complementary for the simple reason that it is far too early in the life-cycle of the of the 3 Party Identity ecosystem to narrow choices down.

There is far too much architecture astronaut-ism (Where the rubber meets the sky and not the road) going on right now, and not enough operational implementation lessons available.

**Comment by marcoscaceres** [comment]
Closing based on https://github.com/WICG/digital-identities/issues/29#issuecomment-1854477507
