### ISSUE TITLE
Add a PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-identities#64]
It would be good if we had a template with check that we need to do before we can merge a Pull Request.

This is what we use for Web Manifest: 
https://github.com/w3c/manifest/blob/main/.github/PULL_REQUEST_TEMPLATE.md

This is what the WHATWG uses:
https://github.com/whatwg/html/blob/main/PULL_REQUEST_TEMPLATE.md

What's important is that we try to implement (and add some tests for) as much as we can as we spec this out.

**Comment by RByers** [comment]
Love it. When do you think we should move to a mode of adding WPTs along with spec (or impl) changes? Hopefully pretty soon? I just don't want to slow down the spec editors too much until it makes sense.

**Comment by marcoscaceres** [comment]
Yes, that would be the idea... right now we get the tests "for free" because all the changes are just Web IDL... but once we start adding prose, we can add tests in parallel.
